# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-02 10:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neighbour', '0004_auto_20191202_0933'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='profile_photo/defaultprofile.jpg', upload_to='profile_photo')),
                ('bio', models.CharField(blank=True, max_length=255)),
                ('contacts', models.CharField(max_length=200)),
                ('join_date', models.DateTimeField(auto_now_add=True)),
                ('hood', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='neighbour.Hood')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='neighbour.User')),
            ],
        ),
    ]
