# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-02 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbour', '0005_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mwenyeji',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.AlterField(
            model_name='hood',
            name='image',
            field=models.ImageField(blank=True, default='hood/hood.jpg', upload_to='hood_photo'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='profile_photo/profile.jpg', upload_to='profile_photo'),
        ),
    ]
