# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-02 12:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neighbour', '0006_auto_20191202_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='Establishment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=20)),
                ('contact', models.CharField(max_length=30)),
                ('image', models.ImageField(blank=True, default='establishment/sample.jpg', upload_to='facilities')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neighbour.User')),
                ('hood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neighbour.Hood')),
            ],
        ),
        migrations.DeleteModel(
            name='Mwenyeji',
        ),
    ]
